version: "3.6"

services:
  sut:
    build:
      context: ./tests/docker-cloud
    privileged: true
    working_dir: /src
    volumes:
      - .:/src:ro
    command: bash -c "
        dockerd-entrypoint.sh >/dev/null 2>&1 &
        /run-tests.sh
      "

